In [1]:
import torch

In [ ]:
print(torch.tensor([1,2,3]))
print(torch.Tensor([[1,2,3], [4,5,6]]))
print(torch.LongTensor([1,2,3]))
print(torch.FloatTensor([1,2,3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])
